# Generated by Django 5.2.3 on 2025-08-05 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='عنوان المسألة')),
                ('description', models.TextField(verbose_name='وصف المسألة')),
                ('difficulty', models.CharField(choices=[('Easy', 'سهل'), ('Medium', 'متوسط'), ('Hard', 'صعب')], db_index=True, default='Easy', max_length=10, verbose_name='مستوى الصعوبة')),
                ('points', models.PositiveIntegerField(default=10, verbose_name='النقاط الممنوحة')),
            ],
            options={
                'verbose_name': 'مسألة',
                'verbose_name_plural': 'المسائل',
                'ordering': ['points'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, verbose_name='بيانات الإدخال')),
                ('expected_output', models.TextField(verbose_name='الناتج المتوقع')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem', verbose_name='المسألة')),
            ],
            options={
                'verbose_name': 'حالة اختبار',
                'verbose_name_plural': 'حالات الاختبار',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField(verbose_name='الكود المُقدَّم')),
                ('status', models.CharField(choices=[('Pending', 'قيد المراجعة'), ('Correct', 'إجابة صحيحة'), ('Wrong', 'إجابة خاطئة'), ('Error', 'خطأ تشغيلي')], db_index=True, default='Pending', max_length=10, verbose_name='الحالة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ التقديم')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقديم',
                'verbose_name_plural': 'التقديمات',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['student', 'problem', 'status'], name='problems_su_student_0657c5_idx')],
            },
        ),
    ]
