# Generated by Django 5.2.3 on 2025-08-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_moderator',
            field=models.BooleanField(default=False, help_text='يحدد ما إذا كان يمكن للمستخدم الإشراف على المحتوى مثل غرف النقاش.', verbose_name='مشرف'),
        ),
    ]
