# Generated by Django 5.2.3 on 2025-08-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(choices=[('m1', 'ذكر 1'), ('m2', 'ذكر 2'), ('m3', 'ذكر 3'), ('f1', 'أنثى 1'), ('f2', 'أنثى 2'), ('f3', 'أنثى 3')], default='m1', max_length=2, verbose_name='الصورة الرمزية'),
        ),
    ]
