# Generated by Django 5.2.3 on 2025-08-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_quiz_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('TEXT', 'محتوى نصي'), ('VIDEO', 'رابط فيديو')], default='TEXT', max_length=10, verbose_name='نوع المحتوى'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='يستخدم إذا كان نوع المحتوى نصيًا.', verbose_name='المحتوى النصي'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='يستخدم إذا كان نوع المحتوى رابط فيديو.', verbose_name='رابط الفيديو'),
        ),
    ]
