# Generated by Django 5.2.3 on 2025-08-07 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='عنوان الشارة')),
                ('description', models.TextField(verbose_name='وصف الإنجاز')),
                ('icon', models.CharField(help_text="مثال: 🎓 أو 'code-branch'", max_length=50, verbose_name='أيقونة (Emoji أو اسم أيقونة)')),
                ('achievement_type', models.CharField(choices=[('LESSONS', 'إكمال الدروس'), ('PROBLEMS', 'حل المسائل'), ('TESTS', 'اجتياز الاختبارات')], max_length=20, verbose_name='نوع الإنجاز')),
                ('threshold', models.PositiveIntegerField(help_text='مثال: حل 10 مسائل', verbose_name='العدد المطلوب')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'badge')},
            },
        ),
    ]
